#! /bin/sh
sxhkd &
wal -i /home/lur/Escritorio/linux/wallpapers/lofi.jpeg
python /home/lur/.config/bspwm/colors.py 

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        1 
bspc config window_gap           5
bspc config focused_border_color "#5B90B3"
bspc config focused_border_width 1

bspc config normal_border_color "#111111"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a burp-StartBurp: state=floating
bspc config focus_follows_pointer true

killall polybar
$HOME/.config/polybar/launch.sh

